blog/config/routes.rb
Rails.application.routes.draw do
  get 'webinar/index'
  get 'alumni/index'
  get 'members/index'
  get 'meet_the_team/index'
  get 'fellows/index'
  get 'company_partners/index'
  get 'jobs/index'
  get 'jobs/individual'
  get 'mentorship/index'
  get 'fellowship_guide/index'
  get 'contact_form/new'
  get 'contact_form/create'
  get 'events/index'
  get 'password_resets/new'
  get 'password_resets/edit--no-test-framework'
  root 'sign_in#new'
  get 'sign_in' =>  'sign_in#new'
  get 'home' => 'home#index'
  get 'events' => 'events'

  get 'sign_up'  => 'users#new'

  resources :sign_in
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :contact_forms

  get '/login' => 'sign_in#new'
  post 'login' => 'sign_in#create'
  delete 'logout' => 'sign_in#destroy'

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/contact_form.rb
class ContactForm < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :file,      :attachment => true
    attribute :message
    attribute :nickname,  :captcha  => true
  
    # Declare the e-mail headers. It accepts anything the mail method
    # in ActionMailer accepts.
    def headers
      {
        :subject => "RTC Portal Contact Form Submission",
        :to => "jbarecelli@rewritingthecode.org",
        :from => %("#{name}" <#{email}>)
      }
    end
  end

blog/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  private
  
  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
  end
end

blog/app/controllers/home_controller.rb
# ruby before_action :require_user, only: [:index, :show]
class HomeController < ApplicationController
  def new
  end
end

blog/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  end

  def individual
  end
end

blog/app/controllers/quickstart.rb
require "google/apis/calendar_v3"
require "googleauth"
require "googleauth/stores/file_token_store"
require "date"
require "fileutils"

OOB_URI = "urn:ietf:wg:oauth:2.0:oob".freeze
APPLICATION_NAME = "Google Calendar API Ruby Quickstart".freeze
CREDENTIALS_PATH = "credentials.json".freeze
# The file token.yaml stores the user's access and refresh tokens, and is
# created automatically when the authorization flow completes for the first
# time.
TOKEN_PATH = "token.yaml".freeze
SCOPE = Google::Apis::CalendarV3::AUTH_CALENDAR_READONLY

##
# Ensure valid credentials, either by restoring from the saved credentials
# files or intitiating an OAuth2 authorization. If authorization is required,
# the user's default browser will be launched to approve the request.
#
# @return [Google::Auth::UserRefreshCredentials] OAuth2 credentials
def authorize
  client_id = Google::Auth::ClientId.from_file CREDENTIALS_PATH
  token_store = Google::Auth::Stores::FileTokenStore.new file: TOKEN_PATH
  authorizer = Google::Auth::UserAuthorizer.new client_id, SCOPE, token_store
  user_id = "default"
  credentials = authorizer.get_credentials user_id
  if credentials.nil?
    url = authorizer.get_authorization_url base_url: OOB_URI
    puts "Open the following URL in the browser and enter the " \
         "resulting code after authorization:\n" + url
    code = gets
    credentials = authorizer.get_and_store_credentials_from_code(
      user_id: user_id, code: code, base_url: OOB_URI
    )
  end
  credentials
end

# Initialize the API
service = Google::Apis::CalendarV3::CalendarService.new
service.client_options.application_name = APPLICATION_NAME
service.authorization = authorize

# Fetch the next 10 events for the user
calendar_id = "primary"
response = service.list_events(calendar_id,
                               max_results:   10,
                               single_events: true,
                               order_by:      "startTime",
                               time_min:      DateTime.now.rfc3339)
puts "Upcoming events:"
puts "No upcoming events found" if response.items.empty?
response.items.each do |event|
  start = event.start.date || event.start.date_time
  puts "- #{event.summary} (#{start})"
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  @user = User.new
  end

  def create
  @user = User.new(user_params)
  if @user.save
    session[:user_id] = @user.id
    redirect_to '/'
  else
    redirect_to '/sign_up'
  end
end
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

blog/app/helpers/alumni_helper.rb
module AlumniHelper
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/contact_form_helper.rb
module ContactFormHelper
end

blog/app/helpers/events_helper.rb
module EventsHelper
end

blog/app/helpers/fellows_helper.rb
module FellowsHelper
end

blog/app/helpers/home_helper.rb
module HomeHelper
end

blog/app/helpers/jobs_helper.rb
module JobsHelper
end

blog/app/helpers/meet_the_team_helper.rb
module MeetTheTeamHelper
end

blog/app/helpers/members_helper.rb
module MembersHelper
end

blog/app/helpers/mentorship_helper.rb
module MentorshipHelper
end

blog/app/helpers/sign_in_helper.rb
module SignInHelper
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/helpers/webinar_helper.rb
module WebinarHelper
end

blog/app/views/layouts/_footer.html.erb
<footer>
    <p class="footer-text"><a href="www.rewritingthecode.org">rewritingthecode.org</a></p>
    <p class="footer-text"><a href="mailto:contact@rewritingthecode.org">contact@rewritingthecode.org</a></p>
</footer>

blog/app/views/layouts/_header.html.erb
<div class="navbar-logo">
<%= link_to image_tag("RTC_Logo.png", alt: "RTC Logo", width: "200", height: "75"), home_url %>
</div>
<div class="dropdown">
    <button onclick="showAbout()" class="dropbtn">About</button>
    <div id="about" class="dropdown-content">
        <a href="#">Meet the Team</a>
        <!--<a href="#">Contact Us</a>-->
        <%= link_to "Contact Us", contact_form_new_path %>
    </div>
</div>
<div class="dropdown">
    <button onclick="showResources()" class="dropbtn">Resources</button>
    <div id="resources" class="dropdown-content">
        <%= link_to "Jobs", jobs_index_path %>
        <a href="/webinar/index">Webinars</a>
        <%= link_to "Events", events_index_path %>
        <%= link_to "Mentorship", mentorship_index_path %>
        <%= link_to "Fellowship Guide", fellowship_guide_index_path %>
    </div>
</div>
<div class="dropdown">
    <button onclick="showDirectory()" class="dropbtn">Directory</button>
    <div id="directory" class="dropdown-content">
        <%= link_to "Company Parthers", company_partners_index_path %>
        <%= link_to "Fellows", fellows_index_path %>
        <%= link_to "Members", members_index_path %>
        <%= link_to "Alumni", alumni_index_path %>
    </div>
</div>
<a href="mailto:?bcc:csoutter@live.unc.edu&subject=Rewriting%20the%20Code%20Application%20Invitation&
body=Hi%20______**,%0d%0dI%20think%20that%20you%20would%20really%20enjoy%20joining%20the%20organization%20Rewriting%20the%20Code. 
%20Rewriting%20the%20Code%20is%20a%20national%20nonprofit%20that%20is%20dedicated%20to%20supporting%20college%20women%20in%20technology!%20With%20over%203000%20members,%20RTC%20creates%20an%20inclusive%20environment
%20for%20all%20women,%20as%20well%20as%20offering%20networking%20opportunities%20with%20partner%20companies,%20access%20to%20resources,%20webinars,%20and%20more!%20Below%20is%20the%20link%20to%20apply%20for%20a%20free%20membership:
%0d%0dhttps://airtable.com/shrNUyBv2hzAMKcvV.%0d%0dPlease%20let%20me%20know%20if%20you%20have%20any%20questions%20and%20I%20hope%20you%20decide%20to%20join%20us!
%0d%0dBest,%0d%0dYour%20Name**
" rel="EMAIL"><button class="refer">
    Refer</button></a>
<div class="dropdown">
    <button onclick="showProfileOptions()" class="profile">C</button>
    <div id="profile" class="dropdown-content">
        <a href="#">Profile Settings</a>
        <a href="#">Sign Out</a>
    </div>
</div>


<script>

    function showAbout() {
        document.getElementById("about").classList.toggle("show");
        document.getElementById("resources").classList.remove("show");
        document.getElementById("directory").classList.remove("show");
        document.getElementById("profile").classList.remove("show");
    }
    function showResources() {
        document.getElementById("about").classList.remove("show");
        document.getElementById("resources").classList.toggle("show");
        document.getElementById("directory").classList.remove("show");
        document.getElementById("profile").classList.remove("show");
    }
    function showDirectory() {
        document.getElementById("about").classList.remove("show");
        document.getElementById("resources").classList.remove("show");
        document.getElementById("directory").classList.toggle("show");
        document.getElementById("profile").classList.remove("show");
    }
    function showProfileOptions() {
        document.getElementById("about").classList.remove("show");
        document.getElementById("resources").classList.remove("show");
        document.getElementById("directory").classList.remove("show");
        document.getElementById("profile").classList.toggle("show");
    }
    window.onclick = function(event) {
        if (!event.target.matches('.dropbtn')) {
            var dropdowns = document.getElementsByClassName("dropdown-content");
            var i;
            for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
            }
        }
    }
</script>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>

blog/app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '>'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>